# Generated by Django 2.0.7 on 2018-07-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathtubPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathtub', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='CountertopPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countertop', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='FireplacePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireplace', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='FlooringPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
