# Generated by Django 2.0.7 on 2018-07-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20180721_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathtubpic',
            name='bathtub',
            field=models.FileField(upload_to='static'),
        ),
    ]
